### ISSUE TITLE
Redirect from Google is not happening

### ISSUE THREAD

**Issue by JuliusJacobsohn** [theirix/google-photo-dedup#2]
I created a new application, created a new OAuth 2.0 Id, downloaded the secret json file and renamed it to client_id.json.
When starting the script, the browser opens and I can select my account and allow all permissions that are needed (I get a warning for having an unverified app but am able to continue). After that I land on a success screen with a "Continue" button and a never-ending loading bar. That's as far as I get. Any ideas?
![image](https://user-images.githubusercontent.com/13764328/74071908-76fff800-4a05-11ea-8a81-99ecc1b4bb93.png)

**Comment by theirix** [comment]
Hello!
Just tried to do a full setup again. First time after granting access I was redirected to the localhost:8080 (seems the OAuth flow expects my app to be able to receive a callback).
Output:
```
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?client_id=CENSORED&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.file+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.metadata+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly&access_type=offline&response_type=code

If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver
```

But then I just restarted a script and I got "The authentication flow has completed." message:
```
Authentication successful.
Storing credentials to /Users/irix/.config/google-photo-dedup/auth-cache.json
Fetching metadata .....................................
Found files: 3719, fetched 37 pages
```

Scripts started to work. So have you tried to just restart a script?

**Comment by JuliusJacobsohn** [comment]
So I assume a file called auth-cache.json needs to be written with the containing response data from the login process. I think this doesn't happen in my case. What type are you credentials in the Google Dev Console? I selected OAuth Client Id -> Other.

**Comment by theirix** [comment]
I went to https://console.cloud.google.com/ and created a new project, then navigated to "API and services" -> "Credentials" and created OAuth Client ID for Other. Then I saved a downloaded  client secret json to `~/.config/google-photo-dedup/client_id.json`. Removed auth-cache.json from the previous experiment.

At the first launch of the script, the webpage with the account chooser was opened. I was able to grant all required permissions to the script and then I was sent to the nonexistent localhost:8080 page.

The auth-cache.json was saved only at the second launch of the script, just after I granted all the permissions again. 

Have you finished the first launch of the script with a concluding redirect to localhost:8080?

**Comment by JuliusJacobsohn** [comment]
> I went to https://console.cloud.google.com/ and created a new project, then navigated to "API and services" -> "Credentials" and created OAuth Client ID for Other. Then I saved a downloaded client secret json to ~/.config/google-photo-dedup/client_id.json. Removed auth-cache.json from the previous experiment.

I did precisely that.
After launching the script for the first time, I'm able to log in and accept the permissions. But the redirect to localhost never happens, see the screenshot above. Launching the script a second time just restarts the process. Launching it with the --noauth_local_webserver parameter I'm asked for a code which I don't have.

**Comment by theirix** [comment]
Yes, redirect to localhost was not handled by the old version. 

Anyway, I have updated the script to the new and recommended Auth library and it should work fine now. Please install requirements from the README and try again. Client token will be saved to `token.pickle` and the line `Storing credentials to` will be printed on success.

**Comment by JuliusJacobsohn** [comment]
Thanks for your work, I was able to get the script to work. I don't want to say everything works yet since it's still fetching metadata, but this issue has been resolved :)
I'd note that I had to change
`from apiclient import discovery`
to
`from googleapiclient import discovery`
because it would not recognize apiclient. Though that might be an issue on my end.

**Comment by theirix** [comment]
Thank you, fixed this import too.

**Comment by NonnoTeo** [comment]
> I went to https://console.cloud.google.com/ and created a new project, then navigated to "API and services" -> "Credentials" and created OAuth Client ID for Other. Then I saved a downloaded client secret json to `~/.config/google-photo-dedup/client_id.json`. Removed auth-cache.json from the previous experiment.
> 

Hello everybody. 
I cannot  understand precisely where this path is:
`~/.config/google-photo-dedup/client_id.json`
I was able to download cliet_id.json file put I don't know where to paste it. 

P.S. I am running on Windows, maybe the config folder is named differently? (Scripts?)

**Comment by theirix** [comment]
Hello!
I think it should go to something like "C:\Users\YourName\.config\google-photo-dedup\client_id.json". Path is [deduced](https://docs.python.org/3.5/library/os.path.html#os.path.expanduser) from %USERPROFILE% or %HOME% env variables.
