### ISSUE TITLE
Ignore removing duplicates larger then prefered

### ISSUE THREAD

**Issue by gweizi** [theirix/google-photo-dedup#3]
```
    if int(prefered.get('size')) < min(int(f.get('size')) for f in duplicates):
        print("Ignore removing duplicates larger then prefered")
        return False

```
I guess you mean to **max** and not **min** (by the print text). 

if there are several duplicates, while one of them has an equal size to the preferred, then this condition will return False, and the delete process will continue.

In the condition before, you return False in case there's at least one instance with camera model. so I assume you want the same behavior for this condition - return False (cancel the deletion process) in case there's at least one duplicated with larger size. therefore, **max** would be better choice.

BTW, Great code!

**Comment by theirix** [comment]
Thank you! The logic in this code should be exactly as you described, fixed and added clarifying comments.
