### ISSUE TITLE
Very cool.

### ISSUE THREAD

**Issue by mavaddat** [theirix/google-photo-dedup#6]
Very cool.
You might also want to edit the instructions in README.md. It says `python3 google-photo-dedup.rb`, but what you rather mean is `python3 google-photo-dedup.py`

_Originally posted by @muety in https://github.com/theirix/google-photo-dedup/issues/1#issuecomment-533211738_
      

The `README.md` still refers to `google-photo-dedup.rb`.

Apparently, you started the project as a Ruby script, but then (wisely IMO) switched to Python.

**Comment by theirix** [comment]
Thank you, good point!
